export const INCREMENT_PRODUCT_QUANTITY = 'INCREMENT_PRODUCT_QUANTITY';
export const DECREMENT_PRODUCT_QUANTITY = 'DECREMENT_PRODUCT_QUANTITY';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const SUM_CART = 'SUM_CART';
export const EMPTY_CART = 'EMPTY_CART';
export const CLOSE_CART = 'CLOSE_CART';
